[package]
name = "rf125"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "driver"
path = "src/main.rs"

[build]
target = "aarch64-unknown-none-softfloat"

[dependencies]
rpi_embedded = "0.1.0"
